class Constant
{
    public const string UserTemperature = "User temperature: {0}";
    public const string YRTemperature = "YR temperature: {0}";
    public const string UserHigher = "Your temperature is higher than YR temperature.";
    public const string UserLower = "Your temperature is lower than YR temperature.";
    public const string UserSame = "Your temperature is the same as YR temperature.";
    public const string TemperatureDifference = "Temperature difference: {0} degrees.";
    public const string LogFile = "log.json";
    public const string Error = "Error: {0}, {1}";
    public const string InvalidInput = "Invalid input. Please enter a valid temperature.";
    public const string EnterTemperature = "Enter your temperature measurement: ";
    public const string BaseUrl = "https://api.met.no/weatherapi/nowcast/2.0/complete?lat=59.9333&lon=10.7166";
    public const string UserAgent = "MyTestApp/0.1";
    public const string AirTemperature = "air_temperature";
    public const string Json = "application/json";
    public const string Prediction = "Prediction: ";
    public const string Positive = "positive";
    public const string Funny = "funny";
    public const string Neutral = "neutral";
    public const string Warning = "warning";
    public const string DataIsAlreadySavedNoNewData = "Data for today has already been saved. You cannot enter new data.";
    public const string LuckyToGuess = "Feeling lucky? Guess the current temperature in Oslo for a prediction for today!";
    public const string SaveData = "Interested in seeing how your guess compares to reality? Save this data along with the actual weather? (yes/no)";
    public const string Note = "Note: It is impossible to enter data twice per one same day.";
    public const string Yes = "yes";
    public const string DataSaved = "Data has been saved.";
    public const string PositivePredictionOne = "The stars are aligned! Today holds the promise of success and positive experiences.";
    public const string PositivePredictionTwo = "A chance encounter could spark a new opportunity. Be open to unexpected connections.";
    public const string PositivePredictionThree = "Your intuition seems particularly sharp today. Trust your gut feeling: give one random student 35/35!";
    public const string FunnyPredictionOne = "Warning: May contain a surge of productivity (or a serious case of the munchies).";
    public const string FunnyPredictionTwo = "Our highly scientific prediction system says you might win the lottery...or maybe just find some good coffee.";
    public const string FunnyPredictionThree = "Brace yourself for a day that's as unpredictable as your morning weather forecast!";
    public const string FunnyPredictionFour = "//This prediction seems legit (maybe)";
    public const string NeutralPredictionOne = "An interesting day unfolds! Buckle up for a mix of challenges and triumphs.";
    public const string NeutralPredictionTwo = "The day seems balanced - perfect for taking things at your own pace.";
    public const string NeutralPredictionThree = "Change is on the horizon! Embrace the unexpected and see where it leads.";
    public const string NeutralPredictionFour = "Stack Overflow will have the answer... eventually.";
    public const string WarningPredictionOne = "Beware of hidden obstacles. Patience and perseverance will be your allies today.";
    public const string WarningPredictionTwo = "A misunderstanding could arise. Choose your words carefully and practice active listening.";
    public const string WarningPredictionThree = "Don't be afraid to ask for help if you need it. A helping hand may be closer than you think.";
    public const string WarningPredictionFour = "If your name is Christian or Tony, you will have a great day, if you buy your friend a muffin. If not, proceed with caution.";
    public const string OpeningLine = "The winds whisper secrets... are you ready to hear a cryptic message for your day?";
    public const int NumberOne = 1;
    public const int NumberThree = 3;
    public const int NumberFive = 5;
}
